{% set name = "less.js" %}
{% set version = "3.5.0" %}
{% set sha256 = "77fbafccf3575735a9176d70a8d6a1945e05065de813ac7a035253ff1b626329" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/less/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g less
  requires:
    - nodejs
   

about:
  home: https://github.com/less/less.js
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The dynamic stylesheet language'
  description: |
    The dynamic stylesheet language
  doc_url: http://lesscss.org/
  dev_url: https://github.com/less/less.js

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
