{% set name = "less.js" %}
{% set version = "3.11.2" %}
{% set sha256 = "2c0e277d4c249737f066ee67b91cf04d99d53e6038fc2852f87cd163de21e17b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/less/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g less
  requires:
    - nodejs


about:
  home: https://github.com/less/less.js
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The dynamic stylesheet language
  description: |
    The dynamic stylesheet language
  doc_url: http://lesscss.org/
  dev_url: https://github.com/less/less.js
