travis:
  secure:
    BINSTAR_TOKEN: WdN5ahKKJ3gDfVb+hY24Q6FX0YzagZ3gnLav1qrfB8siwh4zW6W7luL78XNtsTZvYLs+4Sd4OYpWwOTrn4TXsjRKtuNckG5sCSBtTLGGtm8j0roKAzOocnHhMyHoKHIKvcVEbc2mNLh72t2aVjiuMy607r5Xizr88Fe3ev0FMTNAC4ycXDbbn5zMhwTYwYkG0IxJKdRxd5XdB+xHepGEqs8r6oGjvFsxBlDXKrHH68um4DOiBL4FQcAte5AFuH1+B80YbGiAdEI3U1hUTQKG98sZsLL6Z+1o595HyU1jOXiFhrMxAJEPUc62RtvyeBBmoeDV/wkporaMu/hVw7osUKcYxw05OcmSPE8l7zrruDIV1V3AIMFUgZP5qz5CkMXJ4aJDr32kpudIynHCPsiIamcRj3r3FTZwhiKfqi7B1SajMYuwOep4HAoLUoW+Bl30FvbG8r0GqC9yh2CIqlN1K540kmgRGvDahGOrEgMyxgKLY9qsAH/H+uBdiGy1FqgZivMXbVHZBZXtT27kHWrhv7iAYjCB+hYzkwnqAGau+/3WnGSMarse0heq19+h3eCD/ZIe7UD2fxXAAmC6SU8qDzcRsXP3416BLLAJ4vdegOtNg5xGDyHRhxB3rwPTVRYbTGJUPTMq0poGTECQ9A0rj+a+WsQKGkOGPG4D6Wje4/4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
