travis:
  secure:
    BINSTAR_TOKEN: 2kOgR5JxdY+g15Guc0nTDShKZyjrFHTb8LEU9n0aYQ3EiOZSn2ZgPk9JsP+HLeU+C6ULQDbGIbMwZdAibUCnI5lQQCWnjfISvGo+WmUuyQr/EtNmTifOoOU178HkyUwVWC20cel0IO40IbQbZGw/DCV2D59fRz0kF8shh0eGoKzUq/JOnkhbirHEnrR+pLtHWxuBVPe3UJJDK0WoMsP2OqKJCTduSWJKAdJDkTENtn06V59CZ6xdhowj8amg5XT6TF8HVprC7+m5AV+RKISV9ujOQtZrJ5+TXZVyQbFv97DJRDWU1rACGmkY3bR9I12G65JxmKrIvwFyQJQYV8x0hiqj5ZkXuKsA24I0/RzG8KCdS2Z9aIGL4t4Y1Kem3IAcx/QrEIECwsVoZ4CU6Kn6IUXDxIEVOEC+JOJ0l1i443OsZ/wcefvrWOiNqt2AK9LRADD6ijF1HaZ6dgXfK0qoy20KJS1sY0qIPIdjh2pZ79m/iYN1qjyrwIeQg7WuGjzUFi7OdfJOohOlM+rxK67x7BO76zL3h/hQ/NUqYYo9IuHi3DA187ZEm99WeoD9L7ogv3DaFABNhudbPtk7A0Yqf0avSggLxVvA2Ritjcr2qHaYfi6SrhfhNIofcYeiPraUK38m9r/HUxdzZ9GM0jiJ+ud9LEA7YyTHuDJmRc2TFis=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
