travis:
  secure:
    BINSTAR_TOKEN: DrjTf/w1+LUU8GyDzG8cM6H33oI3l7FjVSAFdz4YICuWS0A2aWh23OFJacRBXAMKWogjbE/91bYJrrnjb5J/I68NMWuGMLxF7d4wsSzMWJb8aRqv3CiXob61Q7YAS+IQwYoF1MnPufRJiep1XC7GUbGldPue2yfIWw+eoGoFuxf4VXmRGauDGVosMB/AT6zagb4wK2xlX/4U7C/YB84+GgJZk5Uz4+vOQvd4ogmpK7Eo8/SvI0z5kU7NlDbHr1tAlp0XTuliD75GAIHfvczyCNYZ0snlZ9I8vGFUI+/CDpe+CKLF+qfOk0eGWhDDds/pvjUfpWcZEuC4blwnEEYpTwLp8uahW3a7Y3HyAek6Zv7GHkFXtT92mBV8sGF0avFxzkqg/SK95nu8kIeaqX837YVBYUG7SidCdiW2ONz76eRPiLbIoD0AxEfc18xSRceB6nEmTDcaFnQjH1W6los51skFzUzI+SKGOscJDEGPqkBdUXJICaxwHWtQdAZYZKrpcG2JOS/HER+IQ3b3F9ebF7W7BwtSA0lOuQBkz3IYsy76wnugRJYS9i9r5/QwyA1DjzsWBpPzel/M7M4OOWWzospKli5pGX5uVYjyQzMpd7u8+yk9yr3GC0DZM50fPEPGC4fcXHTZUaoyuPyfhLpXUrZY5mOJfIbF45JxzCyJUhk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
